CREATE TABLE RESTAURANT(
ID INT AUTO_INCREMENT,
RES_NAME VARCHAR(50),
LOCATION VARCHAR(50),
CUISINE VARCHAR(50),
DISTANCE DOUBLE,
BUDGET DOUBLE
);
CREATE TABLE RESTAURANT_VS_FOOD(
ID INT AUTO_INCREMENT,
RES_ID INT,
FOOD_ID INT
);

INSERT INTO RESTAURANT VALUES(1,'Roasted Pepper','Baranagar','Casual',6,1000);
INSERT INTO RESTAURANT VALUES(2,'The Fit Foodie','Jadavpur','Family',10,500);
INSERT INTO RESTAURANT VALUES(3,'Arsalan Restaurant','Taltala','Casual',10,1200);
INSERT INTO RESTAURANT VALUES(4,'Calcutta 4','ShyamBazar','Casual',15,1200);
INSERT INTO RESTAURANT VALUES(5,'Tandoor Park','Jadavpur','Buffet',26,1000);
INSERT INTO RESTAURANT VALUES(6,'KhanaSutra - Park Prime Kolkata','Jadavpur','Buffet',20,1800);
INSERT INTO RESTAURANT VALUES(7,'The Dugout','Baranagar','Buffet',18,1800);
INSERT INTO RESTAURANT VALUES(8,'Flame And Grill South City','Dhakuria','Buffet',16,800);
INSERT INTO RESTAURANT VALUES(9,'Calcutta 4','Dhakuria','Buffet',5,1000);
INSERT INTO RESTAURANT VALUES(10,'Adda Junction','Baranagar','Buffet',20,1200);

INSERT INTO RESTAURANT_VS_FOOD VALUES(1,1,14);
INSERT INTO RESTAURANT_VS_FOOD VALUES(2,1,2);
INSERT INTO RESTAURANT_VS_FOOD VALUES(3,1,24);
INSERT INTO RESTAURANT_VS_FOOD VALUES(4,1,21);
INSERT INTO RESTAURANT_VS_FOOD VALUES(5,1,17);
INSERT INTO RESTAURANT_VS_FOOD VALUES(6,1,16);
INSERT INTO RESTAURANT_VS_FOOD VALUES(7,1,37);
INSERT INTO RESTAURANT_VS_FOOD VALUES(8,1,20);
INSERT INTO RESTAURANT_VS_FOOD VALUES(9,1,6);
INSERT INTO RESTAURANT_VS_FOOD VALUES(10,1,3);
INSERT INTO RESTAURANT_VS_FOOD VALUES(11,2,1);
INSERT INTO RESTAURANT_VS_FOOD VALUES(12,2,23);
INSERT INTO RESTAURANT_VS_FOOD VALUES(13,2,28);
INSERT INTO RESTAURANT_VS_FOOD VALUES(14,2,18);
INSERT INTO RESTAURANT_VS_FOOD VALUES(15,2,18);
INSERT INTO RESTAURANT_VS_FOOD VALUES(16,2,1);
INSERT INTO RESTAURANT_VS_FOOD VALUES(17,2,9);
INSERT INTO RESTAURANT_VS_FOOD VALUES(18,2,5);
INSERT INTO RESTAURANT_VS_FOOD VALUES(19,2,20);
INSERT INTO RESTAURANT_VS_FOOD VALUES(20,2,5);
INSERT INTO RESTAURANT_VS_FOOD VALUES(21,3,36);
INSERT INTO RESTAURANT_VS_FOOD VALUES(22,3,14);
INSERT INTO RESTAURANT_VS_FOOD VALUES(23,3,7);
INSERT INTO RESTAURANT_VS_FOOD VALUES(24,3,38);
INSERT INTO RESTAURANT_VS_FOOD VALUES(25,3,13);
INSERT INTO RESTAURANT_VS_FOOD VALUES(26,3,2);
INSERT INTO RESTAURANT_VS_FOOD VALUES(27,3,11);
INSERT INTO RESTAURANT_VS_FOOD VALUES(28,3,13);
INSERT INTO RESTAURANT_VS_FOOD VALUES(29,3,33);
INSERT INTO RESTAURANT_VS_FOOD VALUES(30,3,35);
INSERT INTO RESTAURANT_VS_FOOD VALUES(31,4,13);
INSERT INTO RESTAURANT_VS_FOOD VALUES(32,4,27);
INSERT INTO RESTAURANT_VS_FOOD VALUES(33,4,37);
INSERT INTO RESTAURANT_VS_FOOD VALUES(34,4,28);
INSERT INTO RESTAURANT_VS_FOOD VALUES(35,4,23);
INSERT INTO RESTAURANT_VS_FOOD VALUES(36,4,10);
INSERT INTO RESTAURANT_VS_FOOD VALUES(37,4,11);
INSERT INTO RESTAURANT_VS_FOOD VALUES(38,4,39);
INSERT INTO RESTAURANT_VS_FOOD VALUES(39,4,33);
INSERT INTO RESTAURANT_VS_FOOD VALUES(40,4,20);
INSERT INTO RESTAURANT_VS_FOOD VALUES(41,5,36);
INSERT INTO RESTAURANT_VS_FOOD VALUES(42,5,24);
INSERT INTO RESTAURANT_VS_FOOD VALUES(43,5,30);
INSERT INTO RESTAURANT_VS_FOOD VALUES(44,5,1);
INSERT INTO RESTAURANT_VS_FOOD VALUES(45,5,15);
INSERT INTO RESTAURANT_VS_FOOD VALUES(46,5,19);
INSERT INTO RESTAURANT_VS_FOOD VALUES(47,5,8);
INSERT INTO RESTAURANT_VS_FOOD VALUES(48,5,1);
INSERT INTO RESTAURANT_VS_FOOD VALUES(49,5,23);
INSERT INTO RESTAURANT_VS_FOOD VALUES(50,5,34);
INSERT INTO RESTAURANT_VS_FOOD VALUES(51,6,9);
INSERT INTO RESTAURANT_VS_FOOD VALUES(52,6,24);
INSERT INTO RESTAURANT_VS_FOOD VALUES(53,6,17);
INSERT INTO RESTAURANT_VS_FOOD VALUES(54,6,38);
INSERT INTO RESTAURANT_VS_FOOD VALUES(55,6,7);
INSERT INTO RESTAURANT_VS_FOOD VALUES(56,6,7);
INSERT INTO RESTAURANT_VS_FOOD VALUES(57,6,29);
INSERT INTO RESTAURANT_VS_FOOD VALUES(58,6,1);
INSERT INTO RESTAURANT_VS_FOOD VALUES(59,6,6);
INSERT INTO RESTAURANT_VS_FOOD VALUES(60,6,33);
INSERT INTO RESTAURANT_VS_FOOD VALUES(61,7,21);
INSERT INTO RESTAURANT_VS_FOOD VALUES(62,7,28);
INSERT INTO RESTAURANT_VS_FOOD VALUES(63,7,34);
INSERT INTO RESTAURANT_VS_FOOD VALUES(64,7,25);
INSERT INTO RESTAURANT_VS_FOOD VALUES(65,7,17);
INSERT INTO RESTAURANT_VS_FOOD VALUES(66,7,18);
INSERT INTO RESTAURANT_VS_FOOD VALUES(67,7,32);
INSERT INTO RESTAURANT_VS_FOOD VALUES(68,7,11);
INSERT INTO RESTAURANT_VS_FOOD VALUES(69,7,39);
INSERT INTO RESTAURANT_VS_FOOD VALUES(70,7,12);
INSERT INTO RESTAURANT_VS_FOOD VALUES(71,8,34);
INSERT INTO RESTAURANT_VS_FOOD VALUES(72,8,10);
INSERT INTO RESTAURANT_VS_FOOD VALUES(73,8,40);
INSERT INTO RESTAURANT_VS_FOOD VALUES(74,8,9);
INSERT INTO RESTAURANT_VS_FOOD VALUES(75,8,36);
INSERT INTO RESTAURANT_VS_FOOD VALUES(76,8,7);
INSERT INTO RESTAURANT_VS_FOOD VALUES(77,8,24);
INSERT INTO RESTAURANT_VS_FOOD VALUES(78,8,36);
INSERT INTO RESTAURANT_VS_FOOD VALUES(79,8,23);
INSERT INTO RESTAURANT_VS_FOOD VALUES(80,8,31);
INSERT INTO RESTAURANT_VS_FOOD VALUES(81,9,37);
INSERT INTO RESTAURANT_VS_FOOD VALUES(82,9,6);
INSERT INTO RESTAURANT_VS_FOOD VALUES(83,9,24);
INSERT INTO RESTAURANT_VS_FOOD VALUES(84,9,40);
INSERT INTO RESTAURANT_VS_FOOD VALUES(85,9,40);
INSERT INTO RESTAURANT_VS_FOOD VALUES(86,9,11);
INSERT INTO RESTAURANT_VS_FOOD VALUES(87,9,14);
INSERT INTO RESTAURANT_VS_FOOD VALUES(88,9,32);
INSERT INTO RESTAURANT_VS_FOOD VALUES(89,9,19);
INSERT INTO RESTAURANT_VS_FOOD VALUES(90,9,13);
INSERT INTO RESTAURANT_VS_FOOD VALUES(91,10,21);
INSERT INTO RESTAURANT_VS_FOOD VALUES(92,10,40);
INSERT INTO RESTAURANT_VS_FOOD VALUES(93,10,12);
INSERT INTO RESTAURANT_VS_FOOD VALUES(94,10,26);
INSERT INTO RESTAURANT_VS_FOOD VALUES(95,10,17);
INSERT INTO RESTAURANT_VS_FOOD VALUES(96,10,40);
INSERT INTO RESTAURANT_VS_FOOD VALUES(97,10,14);
INSERT INTO RESTAURANT_VS_FOOD VALUES(98,10,22);
INSERT INTO RESTAURANT_VS_FOOD VALUES(99,10,17);
INSERT INTO RESTAURANT_VS_FOOD VALUES(100,10,12);
